version: '3.8'
services:
    main:
        build:
            context: .
            dockerfile: Dockerfile
        command: 'php artisan serve --host=0.0.0.0'
        volumes:
            - .:/app
            -  /app/vendor
        ports:
            - 8000:8000
            - 5173:5173

    postgres:
        image: postgres:13.1-alpine
        container_name: chat_app_dbs
        volumes:
            - "./sourcefiles/postgres:/var/lib/postgresql/data"
        environment:
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_DATABASE}
            - LANG='ja_JP.UTF-8'
        ports:
        - "6543:5432"

    mailhog:
      image: mailhog/mailhog:v1.0.0
      ports:
        - "1025:1025"
        - "8025:8025"
